Model:
    CharSet: [' ', M, '2', c, X, '7', S, v, e, z, t, d, J, w, k, x, H, N, C, E, P,
        '4', u, A, y, a, O, D, '9', j, Q, '3', '0', '8', I, g, o, K, Y, F, q, W, L,
        l, '1', n, p, U, b, h, R, r, i, Z, T, '5', B, f, s, m, '6', V, G]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0 
    Path: C:/Users/Administrator/Documents/GitHub/dddd_trainer/data/images_set
    Project: captcha_simple
    Val: 0.03
Train:
    BATCH_SIZE: 32
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.97, Cost: 0.05, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 1000
